# Generated by Django 5.1.5 on 2025-02-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='1FD579BF', max_length=10),
        ),
    ]
