# Generated by Django 5.1.5 on 2025-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='E596A23B', max_length=10),
        ),
    ]
